language: node_js

node_js:
  - "4.0"
  - "4.1"
  - "4.2"
  - "5.0"
  - "5.1"
  - "5.2"

sudo: false

script: "node_modules/.bin/istanbul cover node_modules/.bin/_mocha -- --recursive -R spec"

after_success: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"