language: node_js

node_js:
  - "4"
  - "5"

sudo: false

script: "node_modules/.bin/istanbul cover node_modules/.bin/_mocha -- --recursive"

after_script: "npm install coveralls && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"